### ISSUE TITLE
Couldn't get remote client config

### ISSUE THREAD

**Issue by ILYAGVC** [nextpost-tech/speedtest-php#1]
PHP Fatal error:  Uncaught Graftype\Speedtest\SpeedtestException: Couldn't get remote client config. Reason: cURL error 0: The cURL request was retried 3 times and did not succeed. The most likely reason for the failure is that cURL was unable to rewind the body of the request and subsequent retries resulted in the same error. Turn on the debug option to see what went wrong. See https://bugs.php.net/bug.php?id=47204 for more information. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://www.speedtest.net/speedtest-config.php in /www/XrayBalancer/vendor/graftype/speedtest-php/src/Speedtest.php:172
Stack trace:
#0 /www/XrayBalancer/vendor/graftype/speedtest-php/src/Speedtest.php(56): Graftype\Speedtest\Speedtest->getRemoteConfig()
#1 /www/XrayBalancer/speedtest.php(8): Graftype\Speedtest\Speedtest->__construct()
#2 {main}
  thrown in /www/XrayBalancer/vendor/graftype/speedtest-php/src/Speedtest.php on line 172

**Comment by sergeykomlev** [comment]
## How to update cURL

To install cURL 7.78 with HTTP2 and ZSTD support on Ubuntu 20.04 and higher versions use following commands:

```console
sudo apt-get update
sudo apt-get install build-essential libcurl4 openssl libssl-dev libssh-dev zlib1g-dev zlib1g libbrotli-dev brotli libkrb5-dev libldap2-dev librtmp-dev libpsl-dev libnghttp2-dev zstd libzstd-dev
cd /usr/local/src
rm -rf curl*
wget https://curl.haxx.se/download/curl-7.78.0.tar.gz
tar -xzvf curl-7.78.0.tar.gz && rm -f curl-7.78.0.tar.gz && cd curl-7.78.0
./configure --prefix=/usr/local --with-ssl --with-nghttp2 --with-libzstd --with-libssh
make -j4
sudo make install
sudo ldconfig
cd ~ && rm -rf curl-7.78.0
curl -V
```

If you already have CURL 7.78 or higher, please check that `zstd` feature exist in your features list.

Use following command:

```console
curl -V
```

Response should contain `zstd` feature in the features list.

```console
curl 7.78.0 ....
Release-Date: ....
Protocols: ...
Features: ... zstd
```

## How to add HTTP3 (QUIC) support to cURL

Caution: It's experimental feature and may not work properly!

To to install newest cURL version with HTTP3 (QUIC) support on Ubuntu 20.04 and higher versions use following commands:

Install required package lists:

```console
sudo apt-get install -y git build-essential libtool libunwind-dev autoconf cmake golang cargo libzstd-dev libbrotli-dev nghttp2
```

Updating Rust on Ubuntu Using the `rustup` Tool:

```console
curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | sh
y
1
source $HOME/.cargo/env
rustc --version
```

Build quiche and BoringSSL:

```console
cd /usr/local/src
git clone --recursive https://github.com/cloudflare/quiche
cd quiche
cargo build --package quiche --release --features ffi,pkg-config-meta,qlog
mkdir quiche/deps/boringssl/src/lib
ln -vnf $(find target/release -name libcrypto.a -o -name libssl.a) quiche/deps/boringssl/src/lib/
```

Build cURL:

```console
cd /usr/local/src
rm -rf curl*
git clone https://github.com/curl/curl
cd curl
autoreconf -fi
./configure LDFLAGS="-Wl,-rpath,$PWD/../quiche/target/release" --with-openssl=$PWD/../quiche/quiche/deps/boringssl/src --with-quiche=$PWD/../quiche/target/release --with-libzstd --with-libssh --with-ssl --with-zstd --with-brotli --with-nghttp2
make
make install
echo "/usr/local/lib" > /etc/ld.so.conf.d/libcurl.conf
ldconfig
curl -V
```

If you see that error: 

```console
error: libSSH libs and/or directories were not found where specified!
```

You can fix tha issue using following commands and re-do step Build cURL:

```console
apt-get install libssl-dev
apt-get install libssh-dev
```

If you see that error: 

```console
error: ‘quiche_stats’ has no member named ‘peer_max_idle_timeout’
```

Solution is [here](https://github.com/curl/curl/pull/12180/files). 

Recompile PHP with newest cURL:

Backup your PHP 7.4 config. After that re-install PHP:

```console
apt-get remove php7.4-curl
apt-get purge php7.4-curl
apt-get install php7.4-curl
service php7.4-fpm restart
```

- I used `php7.4-curl` and `php7.4-fpm` because my PHP version is `7.4`. You may have different version, to find your version please use following command `php --version`.

If in response to that command:

```console
curl --http3 https://quic.aiortc.org/
```

You see: 

```console
<p>
    Congratulations, you loaded this page using HTTP/3!
</p>
```

Thats mean you successfully installed the newest cURL version with HTTP3 (QUIC) support. If not, please Google your issue and try to find a fix.

If this cURL version not working well for you and you have more issues because of that update, please downgrade back to the previous version without HTTP3 (QUIC) support.

**Comment by sergeykomlev** [comment]
Also, are you doing that speedtest from cloud server or with proxy? What proxy type is it?

**Comment by ILYAGVC** [comment]
> Also, are you doing that speedtest from cloud server or with proxy? What proxy type is it?

Thanks!
With Proxy, http
